const getProducts3 = () => [
  {
    vendorKey: 'HomeEssentials', categoryKey: 'home-kitchen',
    name: 'Instant Pot Duo 7-in-1',
    description: '7-in-1 multi-use programmable pressure cooker, slow cooker, rice cooker, steamer, saute pan, yogurt maker and warmer.',
    price: 89, originalPrice: 129, brand: 'Instant Pot', stock: 55, sku: 'IP-DUO-7IN1-6QT',
    ratings: 4.8, reviewCount: 432, featured: true,
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400',
    specifications: [{ key:'Capacity', value:'6 Quart' },{ key:'Functions', value:'7-in-1' },{ key:'Wattage', value:'1000W' }],
    variants: [{ name:'Size', options:['3 Quart','6 Quart','8 Quart'] }],
    tags: ['instant-pot','pressure-cooker','kitchen','cooking'],
  },
  {
    vendorKey: 'HomeEssentials', categoryKey: 'home-kitchen',
    name: 'Dyson V15 Detect Vacuum',
    description: 'The Dyson V15 Detect automatically adapts suction. Laser reveals microscopic dust on hard floors.',
    price: 649, originalPrice: 749, brand: 'Dyson', stock: 25, sku: 'DYS-V15-DET',
    ratings: 4.7, reviewCount: 156, featured: true,
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    specifications: [{ key:'Suction', value:'230 AW' },{ key:'Run Time', value:'Up to 60 min' },{ key:'Weight', value:'3.1 kg' }],
    variants: [{ name:'Color', options:['Yellow/Nickel','Absolute'] }],
    tags: ['dyson','vacuum','cordless','cleaning'],
  },
  {
    vendorKey: 'HomeEssentials', categoryKey: 'home-kitchen',
    name: 'KitchenAid Stand Mixer',
    description: 'The KitchenAid Artisan Series 5-Qt. Stand Mixer with 10 speeds and tilt-head design.',
    price: 379, originalPrice: 449, brand: 'KitchenAid', stock: 30, sku: 'KA-ARTISAN-5QT',
    ratings: 4.9, reviewCount: 287, featured: false,
    images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
    specifications: [{ key:'Capacity', value:'5 Quart' },{ key:'Motor', value:'325 Watt' },{ key:'Speeds', value:'10' }],
    variants: [{ name:'Color', options:['Empire Red','Onyx Black','Ice Blue','Contour Silver','White'] }],
    tags: ['kitchenaid','mixer','baking','kitchen'],
  },
  {
    vendorKey: 'BeautyGlow', categoryKey: 'beauty',
    name: 'La Mer Moisturizing Cream',
    description: 'The legendary Creme de la Mer moisturizer. Powered by the miracle broth, it helps heal dryness.',
    price: 185, originalPrice: 215, brand: 'La Mer', stock: 40, sku: 'LM-CREAM-60ML',
    ratings: 4.8, reviewCount: 312, featured: true,
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
    specifications: [{ key:'Size', value:'60ml / 2 oz' },{ key:'Skin Type', value:'All skin types' },{ key:'Key Ingredient', value:'Miracle Broth' }],
    variants: [{ name:'Size', options:['30ml','60ml','100ml','250ml'] }],
    tags: ['lamer','moisturizer','skincare','luxury'],
  },
  {
    vendorKey: 'BeautyGlow', categoryKey: 'beauty',
    name: 'Charlotte Tilbury Pillow Talk Lipstick',
    description: 'The iconic Pillow Talk lipstick in a universally flattering nude-pink shade.',
    price: 34, originalPrice: 40, brand: 'Charlotte Tilbury', stock: 85, sku: 'CT-LIPS-PT-001',
    ratings: 4.9, reviewCount: 567, featured: true,
    images: ['https://images.unsplash.com/photo-1586495777744-4e6232bf2f9b?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1586495777744-4e6232bf2f9b?w=400',
    specifications: [{ key:'Finish', value:'Satin' },{ key:'Formula', value:'Long-lasting' },{ key:'Weight', value:'3.5g' }],
    variants: [{ name:'Shade', options:['Pillow Talk','Pillow Talk Medium','Pillow Talk Intense'] }],
    tags: ['lipstick','charlotte-tilbury','makeup','beauty'],
  },
  {
    vendorKey: 'SportsPro', categoryKey: 'sports',
    name: 'Lululemon Align Leggings',
    description: 'Made with buttery-soft Nulu fabric. Designed for yoga, these leggings feel like a second skin.',
    price: 98, originalPrice: 128, brand: 'Lululemon', stock: 90, sku: 'LUL-ALIGN-25IN',
    ratings: 4.8, reviewCount: 423, featured: false,
    images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400',
    specifications: [{ key:'Material', value:'Nulu fabric' },{ key:'Length', value:'25 inches' },{ key:'Rise', value:'High Rise' }],
    variants: [{ name:'Size', options:['0','2','4','6','8','10','12','14'] },{ name:'Color', options:['Black','Navy','Heathered Slate','Wisteria Pink'] }],
    tags: ['lululemon','leggings','yoga','activewear'],
  },
  {
    vendorKey: 'SportsPro', categoryKey: 'sports',
    name: 'Hydro Flask 32oz Water Bottle',
    description: 'TempShield double-wall vacuum insulation keeps drinks cold up to 24 hours.',
    price: 44, originalPrice: 55, brand: 'Hydro Flask', stock: 150, sku: 'HF-32OZ-WB',
    ratings: 4.8, reviewCount: 654, featured: false,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
    specifications: [{ key:'Capacity', value:'32 oz / 946ml' },{ key:'Material', value:'18/8 Pro-Grade Stainless Steel' },{ key:'Cold', value:'Up to 24 hours' }],
    variants: [{ name:'Size', options:['18oz','24oz','32oz','40oz'] },{ name:'Color', options:['Black','White','Pacific','Flamingo','Olive'] }],
    tags: ['hydro-flask','water-bottle','sports','hydration'],
  },
  {
    vendorKey: 'AccessoriesPlus', categoryKey: 'accessories',
    name: 'Rolex Submariner Watch',
    description: 'The Submariner is the reference among divers watches. Waterproof to 300m.',
    price: 8999, originalPrice: 9500, brand: 'Rolex', stock: 5, sku: 'ROL-SUB-41MM',
    ratings: 5.0, reviewCount: 34, featured: true,
    images: ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600','https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=400',
    specifications: [{ key:'Case Size', value:'41mm' },{ key:'Water Resistance', value:'300m' },{ key:'Movement', value:'Automatic' }],
    variants: [{ name:'Bezel', options:['Black','Blue','Green'] }],
    tags: ['rolex','watch','luxury','submariner'],
  },
  {
    vendorKey: 'AccessoriesPlus', categoryKey: 'accessories',
    name: 'Louis Vuitton Neverfull MM',
    description: 'The iconic Louis Vuitton Neverfull tote in Monogram canvas. Spacious and versatile.',
    price: 1550, originalPrice: 1700, brand: 'Louis Vuitton', stock: 8, sku: 'LV-NEVERFULL-MM',
    ratings: 4.9, reviewCount: 67, featured: true,
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
    specifications: [{ key:'Material', value:'Monogram Canvas' },{ key:'Dimensions', value:'31 x 28 x 14 cm' }],
    variants: [{ name:'Size', options:['PM','MM','GM'] }],
    tags: ['louis-vuitton','bag','tote','luxury'],
  },
  {
    vendorKey: 'BookWorld', categoryKey: 'books',
    name: 'Atomic Habits by James Clear',
    description: 'An Easy and Proven Way to Build Good Habits and Break Bad Ones. The #1 NYT bestseller.',
    price: 16, originalPrice: 27, brand: 'Avery', stock: 200, sku: 'BK-ATOMIC-HABITS',
    ratings: 4.9, reviewCount: 1243, featured: true,
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    specifications: [{ key:'Author', value:'James Clear' },{ key:'Pages', value:'320' },{ key:'Publisher', value:'Avery' }],
    variants: [{ name:'Format', options:['Hardcover','Paperback','Kindle'] }],
    tags: ['book','self-help','habits','productivity'],
  },
  {
    vendorKey: 'BookWorld', categoryKey: 'books',
    name: 'The Psychology of Money',
    description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel.',
    price: 14, originalPrice: 22, brand: 'Harriman House', stock: 180, sku: 'BK-PSYCH-MONEY',
    ratings: 4.8, reviewCount: 876, featured: false,
    images: ['https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400',
    specifications: [{ key:'Author', value:'Morgan Housel' },{ key:'Pages', value:'256' }],
    variants: [{ name:'Format', options:['Hardcover','Paperback','Kindle'] }],
    tags: ['book','finance','money','investing'],
  },
];
module.exports = getProducts3;
