const getProducts2 = () => [
  {
    vendorKey: 'FashionHub', categoryKey: 'mens-clothing',
    name: 'Classic Oxford Button-Down Shirt',
    description: 'Premium cotton Oxford shirt with a classic button-down collar. Perfect for business casual.',
    price: 59, originalPrice: 89, brand: 'FashionHub', stock: 120, sku: 'FH-SHIRT-OXF-001',
    ratings: 4.5, reviewCount: 87, featured: false,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400',
    specifications: [{ key:'Material', value:'100% Cotton' },{ key:'Fit', value:'Regular Fit' }],
    variants: [{ name:'Size', options:['XS','S','M','L','XL','XXL'] },{ name:'Color', options:['White','Light Blue','Navy','Pink'] }],
    tags: ['shirt','mens','oxford','formal'],
  },
  {
    vendorKey: 'FashionHub', categoryKey: 'mens-clothing',
    name: 'Slim Fit Chino Pants',
    description: 'Modern slim fit chino pants crafted from stretch cotton blend.',
    price: 69, originalPrice: 99, brand: 'FashionHub', stock: 95, sku: 'FH-CHINO-SLM-001',
    ratings: 4.4, reviewCount: 63, featured: false,
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400',
    specifications: [{ key:'Material', value:'97% Cotton, 3% Elastane' },{ key:'Fit', value:'Slim Fit' }],
    variants: [{ name:'Size', options:['28x30','30x30','32x30','32x32','34x32'] },{ name:'Color', options:['Khaki','Navy','Olive','Stone'] }],
    tags: ['pants','chino','mens','slim'],
  },
  {
    vendorKey: 'FashionHub', categoryKey: 'womens-clothing',
    name: 'Floral Wrap Midi Dress',
    description: 'Elegant floral wrap dress with a flattering silhouette. Perfect for summer occasions.',
    price: 79, originalPrice: 119, brand: 'FashionHub', stock: 75, sku: 'FH-DRESS-WRP-001',
    ratings: 4.7, reviewCount: 142, featured: true,
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400',
    specifications: [{ key:'Material', value:'100% Viscose' },{ key:'Length', value:'Midi' }],
    variants: [{ name:'Size', options:['XS','S','M','L','XL'] },{ name:'Color', options:['Blue Floral','Pink Floral','Green Floral'] }],
    tags: ['dress','womens','floral','midi','summer'],
  },
  {
    vendorKey: 'FashionHub', categoryKey: 'womens-clothing',
    name: 'High-Waist Skinny Jeans',
    description: 'Classic high-waist skinny jeans with comfortable stretch fabric.',
    price: 89, originalPrice: 129, brand: 'FashionHub', stock: 110, sku: 'FH-JEANS-HW-001',
    ratings: 4.6, reviewCount: 198, featured: false,
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400',
    specifications: [{ key:'Material', value:'92% Cotton, 6% Polyester, 2% Elastane' },{ key:'Fit', value:'Skinny' }],
    variants: [{ name:'Size', options:['24','25','26','27','28','29','30'] },{ name:'Color', options:['Dark Blue','Light Blue','Black','White'] }],
    tags: ['jeans','womens','skinny','high-waist'],
  },
  {
    vendorKey: 'ShoeMart', categoryKey: 'shoes',
    name: 'Nike Air Max 270',
    description: 'The Nike Air Max 270 delivers visible cushioning under every step.',
    price: 149, originalPrice: 180, brand: 'Nike', stock: 60, sku: 'NK-AM270-001',
    ratings: 4.7, reviewCount: 276, featured: true,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600','https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    specifications: [{ key:'Upper', value:'Mesh and synthetic' },{ key:'Sole', value:'Rubber' },{ key:'Cushioning', value:'Air Max 270 unit' }],
    variants: [{ name:'Size', options:['7','7.5','8','8.5','9','9.5','10','10.5','11','12'] },{ name:'Color', options:['Black/White','White/Red','Blue/White','All Black'] }],
    tags: ['nike','sneakers','airmax','running'],
  },
  {
    vendorKey: 'ShoeMart', categoryKey: 'shoes',
    name: 'Adidas Ultraboost 23',
    description: 'Experience incredible energy return with Boost midsole technology.',
    price: 189, originalPrice: 220, brand: 'Adidas', stock: 45, sku: 'ADI-UB23-001',
    ratings: 4.8, reviewCount: 189, featured: true,
    images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600'],
    thumbnail: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400',
    specifications: [{ key:'Upper', value:'Primeknit+' },{ key:'Midsole', value:'Boost' },{ key:'Outsole', value:'Continental Rubber' }],
    variants: [{ name:'Size', options:['6','6.5','7','7.5','8','8.5','9','9.5','10','11'] },{ name:'Color', options:['Core Black','Cloud White','Solar Red'] }],
    tags: ['adidas','ultraboost','running','sneakers'],
  },
];
module.exports = getProducts2;
